# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_reduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\"\"\n\ndata_point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\xb6\x01\n\x1cmaster_to_mapper_task_assign\x12\x13\n\x0bstart_index\x18\x01 \x01(\x05\x12\x11\n\tend_index\x18\x02 \x01(\x05\x12\x1f\n\nk_clusters\x18\x03 \x03(\x0b\x32\x0b.data_point\x12 \n\x0b\x64\x61ta_points\x18\x04 \x03(\x0b\x32\x0b.data_point\x12\t\n\x01M\x18\x05 \x01(\x05\x12\t\n\x01R\x18\x06 \x01(\x05\x12\t\n\x01k\x18\x07 \x01(\x05\x12\n\n\x02id\x18\x08 \x01(\x05\"z\n\x1dmaster_to_reducer_task_assign\x12\x17\n\x0fpartition_index\x18\x01 \x01(\x05\x12\x13\n\x0bmapper_port\x18\x02 \x03(\x05\x12\t\n\x01M\x18\x03 \x01(\x05\x12\t\n\x01R\x18\x04 \x01(\x05\x12\t\n\x01k\x18\x05 \x01(\x05\x12\n\n\x02id\x18\x06 \x01(\x05\"V\n\x1cmapper_to_reducer_data_point\x12\x0b\n\x03key\x18\x01 \x01(\x02\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.data_point\x12\r\n\x05\x63ount\x18\x03 \x01(\x02\"8\n%master_to_mapper_task_assign_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"9\n&master_to_reducer_task_assign_response\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n#mapper_to_master_file_read_response\x12\r\n\x05point\x18\x01 \x01(\t\"6\n\x1breducer_to_mapper_file_read\x12\x17\n\x0fpartition_index\x18\x01 \x01(\x05\"k\n$reducer_to_mapper_file_read_response\x12\x32\n\x0b\x64\x61ta_points\x18\x01 \x03(\x0b\x32\x1d.mapper_to_reducer_data_point\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xbe\x01\n\x06Mapper\x12V\n\x0b\x61ssign_task\x12\x1d.master_to_mapper_task_assign\x1a&.master_to_mapper_task_assign_response\"\x00\x12\\\n\x13give_partition_data\x12\x1c.reducer_to_mapper_file_read\x1a%.reducer_to_mapper_file_read_response\"\x00\x32k\n\x07Reducer\x12`\n\x13reducer_assign_task\x12\x1e.master_to_reducer_task_assign\x1a\'.master_to_reducer_task_assign_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA_POINT']._serialized_start=20
  _globals['_DATA_POINT']._serialized_end=54
  _globals['_MASTER_TO_MAPPER_TASK_ASSIGN']._serialized_start=57
  _globals['_MASTER_TO_MAPPER_TASK_ASSIGN']._serialized_end=239
  _globals['_MASTER_TO_REDUCER_TASK_ASSIGN']._serialized_start=241
  _globals['_MASTER_TO_REDUCER_TASK_ASSIGN']._serialized_end=363
  _globals['_MAPPER_TO_REDUCER_DATA_POINT']._serialized_start=365
  _globals['_MAPPER_TO_REDUCER_DATA_POINT']._serialized_end=451
  _globals['_MASTER_TO_MAPPER_TASK_ASSIGN_RESPONSE']._serialized_start=453
  _globals['_MASTER_TO_MAPPER_TASK_ASSIGN_RESPONSE']._serialized_end=509
  _globals['_MASTER_TO_REDUCER_TASK_ASSIGN_RESPONSE']._serialized_start=511
  _globals['_MASTER_TO_REDUCER_TASK_ASSIGN_RESPONSE']._serialized_end=568
  _globals['_MAPPER_TO_MASTER_FILE_READ_RESPONSE']._serialized_start=570
  _globals['_MAPPER_TO_MASTER_FILE_READ_RESPONSE']._serialized_end=622
  _globals['_REDUCER_TO_MAPPER_FILE_READ']._serialized_start=624
  _globals['_REDUCER_TO_MAPPER_FILE_READ']._serialized_end=678
  _globals['_REDUCER_TO_MAPPER_FILE_READ_RESPONSE']._serialized_start=680
  _globals['_REDUCER_TO_MAPPER_FILE_READ_RESPONSE']._serialized_end=787
  _globals['_MAPPER']._serialized_start=790
  _globals['_MAPPER']._serialized_end=980
  _globals['_REDUCER']._serialized_start=982
  _globals['_REDUCER']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
